# Generated by Django 2.1 on 2018-08-26 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_adopcion', models.DateTimeField(blank=True, null=True)),
                ('en_adopcion', models.BooleanField(default=True)),
            ],
        ),
    ]
