# Generated by Django 2.1 on 2018-08-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animales',
            new_name='Animal',
        ),
    ]
